name: Deploy S3 File API

on:
  push:
    branches: [ main ]
    paths:
      - 's3-file-api/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache Node modules
      uses: actions/cache@v2
      with:
        path: 's3-file-api/**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('s3-file-api/**/package-lock.json') }}

    - name: Use Node.js 20.x
      uses: actions/setup-node@v1
      with:
        node-version: 20.x
    
    - name: Remove .build directories from deployment
      run: |
        rm -rf ./s3-file-api/.build
      working-directory: ./s3-file-api

    - name: Install dependencies
      run: npm install
      working-directory: ./s3-file-api

    - name: Serverless Deploy
      run: npx serverless deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_CLOUDFRONT_CDN_URL: ${{ secrets.AWS_CLOUDFRONT_CDN_URL }}
      working-directory: ./s3-file-api