name: Deploy DynamoDB CRUD API

# controls when the action will run. Triggers the workflow on push or pull request events
on:
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    name: deploy

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

      # Cache node_modules
    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}

        # Use Node.js 14.x
      - name: Use Node.js 14.x
        uses: actions.setup-node@v1
        with:
          node-version: 14.x

        # Install dependencies
      - name: Install dependencies
        run: yarn install

      # Deploy the serverless application
      - name: serverless deploy
        uses: serverless/serverless-action@master
        with:
          args: deploy
        env:
          # AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY are stored in GitHub secrets
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}